package com.imjustdoom.doomsrecordcollection.block;

import com.imjustdoom.doomsrecordcollection.block.entity.RecordDisplayEntity;
import com.imjustdoom.doomsrecordcollection.item.ModItems;
import com.imjustdoom.doomsrecordcollection.platform.RegistryWrapper;
import com.imjustdoom.doomsrecordcollection.platform.Services;
import net.minecraft.core.Registry;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockBehaviour;

import java.util.*;
import java.util.function.Supplier;

public class ModBlocks {
    public static final List<RegistryWrapper<RecordDisplay>> RECORD_DISPLAYS = new ArrayList<>();

    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLACK_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("black_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BLUE_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("blue_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> BROWN_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("brown_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> CYAN_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("cyan_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GRAY_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("gray_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> GREEN_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("green_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_BLUE_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_blue_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIGHT_GRAY_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("light_gray_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> LIME_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("lime_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> MAGENTA_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("magenta_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> ORANGE_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("orange_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PINK_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("pink_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> PURPLE_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("purple_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> RED_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("red_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> WHITE_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("white_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_SPRUCE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_spruce_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.SPRUCE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_BIRCH_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_birch_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BIRCH_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_JUNGLE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_jungle_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.JUNGLE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_ACACIA_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_acacia_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.ACACIA_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_DARK_OAK_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_dark_oak_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.DARK_OAK_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_MANGROVE_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_mangrove_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.MANGROVE_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_CHERRY_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_cherry_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CHERRY_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_BAMBOO_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_bamboo_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.BAMBOO_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_CRIMSON_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_crimson_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.CRIMSON_PLANKS).noOcclusion()));
    public static final RegistryWrapper<RecordDisplay> YELLOW_WOOL_WARPED_PLANKS_RECORD_DISPLAY = registerRecordDisplay("yellow_wool_warped_planks_record_display", () -> new RecordDisplay(BlockBehaviour.Properties.copy(Blocks.WARPED_PLANKS).noOcclusion()));

    public static final RegistryWrapper<BlockEntityType<RecordDisplayEntity>> RECORD_DISPLAY_ENTITY;

    private static RegistryWrapper<RecordDisplay> registerRecordDisplay(String id, Supplier<RecordDisplay> block) {
        RegistryWrapper<RecordDisplay> wrapper = registerBlock(id, block);
        RECORD_DISPLAYS.add(wrapper);
        return wrapper;
    }

    private static <T extends Block> RegistryWrapper<T> registerBlock(String id, Supplier<T> block) {
        RegistryWrapper<T> registeredBlock = Services.PLATFORM.registerBlock(id, block);
        registerBlockItem(id, registeredBlock);
        return registeredBlock;
    }

    private static <T extends Block> RegistryWrapper<Item> registerBlockItem(String name, RegistryWrapper<T> block) {
        return ModItems.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
    }

    private static <T extends BlockEntity> RegistryWrapper<BlockEntityType<T>> registerBlockEntity(String id, Supplier<BlockEntityType<T>> blockEntity) {
        return Services.PLATFORM.registerBlockEntity(id, blockEntity);
    }

    public static void init() {
    }

    static {
        System.out.println(RECORD_DISPLAYS.size());
        System.out.println(RECORD_DISPLAYS);
        RECORD_DISPLAY_ENTITY = registerBlockEntity("record_display", () -> BlockEntityType.Builder.of(
                RecordDisplayEntity::new,
                RECORD_DISPLAYS.stream().map(RegistryWrapper::get).toArray(Block[]::new)
        ).build(null));
    }
}
